name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2  # Adjust to your region

    - name: Copy files via SCP
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.HOST_DNS }}  # Update to public DNS name or IP
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}  # Your private SSH key
        source: "./"  # Adjust the source directory if needed
        target: "/var/www/html"  # Target directory on the EC2 instance

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST_DNS }}  # Update to public DNS name or IP
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}  # Your private SSH key
        script: |
          sudo systemctl restart httpd  # Restart Apache to apply changes
