name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-user@ip-172-31-85-67 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          rsync -r --delete ./path/to/your/code ec2-user@ip-172-31-85-67:/var/www/html/
