name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for deployment

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test SSH Connectivity
        run: |
          ssh -v ec2-user@ip-172-31-85-67.ec2.internal  # Replace with your EC2 hostname

      - name: Deploy to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./var/www/html/* ec2-user@ip-172-31-85-67.ec2.internal:/var/www/html/

      - name: Post-Deployment Tasks (optional)
        run: |
          # Add any necessary post-deployment steps, such as restarting services
